### ISSUE TITLE
Change extension `Lookup` link to use official wiki instead of Fandom wiki

### ISSUE THREAD

**Issue by Nightfirecat** [pepijnverburg/osrs-runelite-twitch-live-loadout-plugin#110]
Fandom wiki has not been the "official" community wiki for a long time; if the links could refer to https://oldschool.runescape.wiki instead, that would be great.

**Comment by Nightfirecat** [comment]
Apologies, I was apparently misled about this--this ought to be linking to the site in the original post and is fine as-is.

**Comment by pepijnverburg** [comment]
Thanks for taking the time to report this @Nightfirecat and good to hear it was already working properly in hindsight! Also smart to report it here, because the Twitch Extension front-end is closed-source. 

May I ask where you got the report? During a stream? Good to know if there are sources I dont know about due to the vast amount of users atm :)

**Comment by Nightfirecat** [comment]
I wish it were for that good a reason. It was some banter with a wiki admin that I overheard, where supposedly this extension was linking to the fandom site, so it was entirely made up to rib them

**Comment by pepijnverburg** [comment]
@Nightfirecat Ah haha, still good to know and hopefully they now know it is linking correctly! Thanks again for having an ear out for the extension.
