### ISSUE TITLE
UIM storage

### ISSUE THREAD

**Issue by myceliated** [pepijnverburg/osrs-runelite-twitch-live-loadout-plugin#48]
Could there be a way to show contents of the looting bags, seedbox and death storages? Would be really nice for UIM streamers.

**Comment by pepijnverburg** [comment]
Hi there, thanks for the suggestion! What would you think would be a good way of showing these storage boxes? A dedicated tab like the current inventory / equipment / bank one? Or an overview that is visible when hovering over the looting bag / seedbox in the inventory tab? Been considering this for the rune pouch as well, would be nice to find a shared way to make it work for all of these items at once.

For the death storages I see quite a challenge, because there are a few to take into account.. Each container for items requires quite some work to implement with both the Runelite Plugin and Twitch Extension.

**Comment by pepijnverburg** [comment]
Closed due to inactivity, will look at this feature later. For now collection log has priority.
