### ISSUE TITLE
Feature Request - Leagues Support

### ISSUE THREAD

**Issue by maxrenke** [pepijnverburg/osrs-runelite-twitch-live-loadout-plugin#52]
I was thinking about building a Twitch Extension for Leagues that is able to show the viewer what fragments are currently equipped. Your extension would support this functionality perfectly!

Essentially you would add a new tab for fragments, read the fragments from the fragment interface when it is opened, and then make the fragments viewable. Depending on what information is shown in the interface, the extension could even display the active set bonuses.

**Comment by pepijnverburg** [comment]
Hi there! Great suggestion, I was thinking about this as well myself. Challenge is to find the time of course, but with the current syncing framework in place it is very much doable. 

Do you know whether there are already things known about how the relics and stuff are exposed in the client API? Perhaps based on previous leagues?

Also, last leagues Jagex implemented an overlay to the left of the screen where all the active perks were shown. I was planning on integrating it back then as well, but cancelled that plan because Jagex was already doing it themselves. Did you come across any of those plans? Have not seen it in the reveals until now.

Happy to work together if you already have some knowledge ready. The Twitch extension currently has around 10k users each day, so might be worthwhile looking into this!

**Comment by pepijnverburg** [comment]
Leagues is only going to be there a few weeks, but due to time limitations not possible to work on these features for this leagues. Renamed to more general discussion about how to approach and generalise functionality for future Leagues.

**Comment by pepijnverburg** [comment]
@maxrenke I have recently been looking at preparing for a next possible League and I noticed some Varbits that relate to the relic slots that seem to be a permanent addition (see: https://static.runelite.net/api/runelite-api/net/runelite/api/Varbits.html#LEAGUE_RELIC_1). 

Have you been looking at the API's for the last few leagues before looking at this plugin and Twitch extension? And if yes, are these things indeed being re-use across leagues? This would make it more interesting to have some integrations possible instead of building it from scratch each league.

**Comment by pepijnverburg** [comment]
Closing this as it was added to the current main branch (not released yet). Made in such a way to support future leagues and other seasonals (like DMM) as well.

https://github.com/pepijnverburg/osrs-runelite-twitch-live-loadout-plugin/assets/15874104/ce6ed936-feae-47da-88f0-0541fa169a49
