### ISSUE TITLE
No longer in the plugin hub?

### ISSUE THREAD

**Issue by ChymistryTTV** [pepijnverburg/osrs-runelite-twitch-live-loadout-plugin#54]
I cannot find this plugin in the plugin hub. Has it stopped working? I really enjoyed it.

**Comment by pepijnverburg** [comment]
Hi @ChymistryTTV, glad to hear you have been enjoying the plugin! That is correct unfortunately :( There are a couple of things that caused this: 
(1) RuneLite was updated causing a couple of helper functions causing the Plugin to crash.
(2) The plugin was logging too much when the Twitch token you put in was expired. This was causing the RuneLite logging system to lag. 
(3) With the inventory rework of Jagex a few weeks back I'm testing a bit more before the new release.
(4) This year Twitch deprecated some API end-points this plugin was using. Because of this I also submitted a new Twitch Extension, which is in review as we speak. Once this one is accepted I will finish updating this plugin so I can make sure it works nicely with the latest Twitch Extension.

I prefer to have all of this batched in one update (and therefore one batch of testing), but this means it also takes a little longer than I would want ;) Hope this clears some things up. 

Finally, some streamers could not easily contact me (Twitch hides the support email a bit for the extension and not everyone has GitHub). So I got to setup a Discord (yep, yet another Discord). Have not been actively communicating it, but if you want to join to stay up to date: https://discord.gg/3Fjm5HTFGM

Will keep this issue open to keep you and others posted.
